apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: teleconetworks.poc.zinkworks.com
spec:
  scope: Namespaced
  group: poc.zinkworks.com
  names:
    kind: TelecoNetwork
    plural: teleconetworks
    singular: teleconetwork
    shortNames:
      - tna
      - tn
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            name:
              type: string
      additionalPrinterColumns:
        - name: Duration
          type: string
          priority: 0
          jsonPath: .spec.duration
          description: For how long the pod should sleep.
        - name: Message
          type: string
          priority: 0
          jsonPath: .status.sample_msg.text
          description: As returned from the handler (sometimes).
        - name: PostRequest
          type: string
          priority: 0
          jsonPath: .status.post_call.request
          description: rest call response
        - name: PutRequest
          type: string
          priority: 0
          jsonPath: .status.put_call.request
          description: put rest call response
